#+TITLE:Bibliografia História da Música

* Bibliografia Geral [/] 


- [ ] BRAUN, Hans-Joachim, [ed.] (2002) Music and Technology in the Twentieth Century, Baltimore, The John Hopkins University Press;

- [ ] DELIÈGE, Céletin (2003) Cinquante ans de modernité musicale: de Dramstadt à l’IRCAM, Sprimont, Mardaga éditeur;

- [ ] MILNER, Greg (2009) Perfecting Sound Forever, The Story of Recorded Music, London, Granta Publications;

- [ ] TAYLOR, Timothy D. (2001) Strange Sounds: Music, Technology and Culture, New York, Routledge;

- [ ] TOYNBEE, Jason (2000) Making Popular Music: musicians, institutions, aesthetics, London, Arnold;

- [ ] KETTLEWELL, Ben. (2002) Electronic Music Pioneers, ProMusic Press.

- [ ] HOLMES, Thomas (2002) Electronic and Experimental Music: Pioneers in Technology and Composition, London, Psychology Press: Routledge;

- [ ] PATTESON, Thomas (2016) Instruments for New Music: Sound, Technology, and Modernism, Oakland, University of California Press

- [ ] HOSKEN, Dan (2011) An Introduction to Music Technology. California State University, Northridge; Routledge.   
