#+AUTHOR: Gonçalo Alegria
#+EMAIL: g.alegria@gmail
#+TITLE: Teoria e Método das Ciências Musicais
#+OPTIONS: toc:nil num:nil





* Aula de dia <2017-09-18 Mon>

Professor Manuel Pedro Ferreira

John Sloboda <2017-10-12 Thu>

Password Moodle: cantus


****** Luisa Rocha - Iconografia Musical, dará aula no dia <2017-10-02 Mon>

****** Rui (?) dará a aula de <2017-09-25 Mon>


** Alguma Bibliografia

_The Craft of Research_ - Wayne C. Booth

_Music and Knowledge, A performers prespective_ - Per Dahl

_Musicologia Série Dialogos Com o Som_ (ensaios)

** Livros do Próprio

_Interpretação Musical Teoria e Prática_

_Dez Compositores Portugueses_

* Fontes

Investigação de uma Fontes

Primeira parte ser a teoria musical, trabalho de localização das fontes teoricas

Cancioneiro | T. Polifónicas

Descobre que não há uma rerodução fiel do Cancioneiro

Faz-se enquadramento:

Qaul o pensamento pot detrás de uma transcrição musical?


_Teoria da Interpretação_ - Theodor Adorno

*** *UMA QUESTÃO POLÍTICA*

a análise musical existe tambem para a valorização histórica.


(restauro eum pergaminho) o facsmile oferece mais infromção | perdeu-se 10% do original. a Música portuguesa  mais antiga de que se tem conhecimento.

Tentativa de contextualidade com as tradições da época no sentido de se colmatar as falhas, usando trabalho posterior  para /inserir/.

Cantigas de Santa Maria <-> Tradição Árabe-andaluz

** A JAZZ-BAND
Exposição sobre representações de etnia na era da JAzz-Band caminho através da ilustração e fotografia da época: 

O ilustrador tem um papel activo/selectivo

Candido Carneiro == Pixinguinha
Faz o mesmo ao Dodecafonismo que o Pixinguinha fez ao Jazz-Band.
