+#TITLE: TEORIA e METODO aula 4
9 de Outubro

* Definição do objecto: 
	- como definir esse objecto d estudo. 

O que fazemos a partir da definição do objecto

** *EXEMPLO:* Banda Filarmónica:
- Há arquivo organizado? Sim
- Que tipo de documentos? (Que registo há, de onde vem a música)
- O que vamos estudar? Os repertórios?
- A relação com a comunidade. (Pesquizar outro tipio de informação)

Fazer inquéritos fichas normalizadas.
- Qual é a relação inter-geracional dentro da banda.
- Tem uma escola associada?

- Podemos ou não fazer um estudo diacrónico, 

** *Sub exemplo:* 
- Temos de limitar o nosso projecto em função daquilo que. Conseguimos extrair.
- De onde vêm os músicos: São locais? São de outras aldeias? 
- Há gravações? Registos como cartões de visita?

*Há uma série de perguntas possíveis de levantar. Destas n perguntas só são respondíveis n-x perguntas.*

- a relação entre a banda e a entidade religiosa. Quais são as condicionantes, quem é que escolhe o repertório.

- Relaçãoentre profissionalismo e amadorismo.
- Até que ponto é que a componente profissional influencia a banda e o seu repertório. (Que músicos)
- 


* Exemplo dois: Que música se passa nos bares de praia?
- Isto é significante?
- 

——————————

* A questão da pergunta

Do interesse ao tópico [craft of research]

A investigação parte da capacidade de interpretação e este parte de um interesse. 

———————————

* Exemplo três: SPA
- Que registos posso investigar?
Temos de ter uma q especifica
- Queremos investigar a musica registada 50 e 60: Porquê? Ver tendências, a representatividade das várias culturas nessa musica. 
- Corremos o risco de demorar a chegar ao arquivo e que este está incompleto.



Estudos de caso. 
Mac -ze mario branco - varios programs dos anos oitenta. 

Soundscape Ecology: 

Musica enquanto sinal.

Os sinos: podem ser visto scomo música ou como sinal, muitas veze sé conheciod como sinal.

A fomra como a soicendae dse apropria do som.

Paisagem Sonora de Fortaleza ao longo do século 20

* 2ª Parte

The Cultural Study of Music. Martin Clayton, Trevor Herbert, Richard Middleton.
 Pag. 40.



Consciência Epistemológica, desenvolver, como se constrói uma investigação que pretende acrescentar algo ao conhecimento.

Critica 


Aquilo que fazemos com os dados é que produz a evidência: FALSE FRIENDS



Colóquio sobre a paisagem sonora universidade de Évora.

Historia da Ciência

Não excluem a crença porque os axiomas não tem de ser provado (?)

O que sai no teste é a capacidade de pegar em situações e exercer uma pensamento crítico.

Para exercitar a capacidade critica precisamos de ir lendo uma série de coisas para ficarmos mais cientes da forma ccomop a discilplina é pensada academicamente.

THe Hipotetic Deductive Method pagina 55, Music Knowledge.


Se estudamos uma coisa ganhamos conhecimento e perdemos inocência.

Os métodos podem ser aplicados dentro de determinados limites.

*Escolher coisas que nos podem ser úteis.*
Sobretudo pensar como o conhecimento se constrói.
 
